### PR TITLE
data-target conflict bootstrap js

### PR DESCRIPTION
**Pull request by matthieumota**

### CODE REVIEW

**Comment by macdonaldr93** [comment]
Hey! Thanks for pushing this, just wondering what the conflict is? What happens when there's a conflict? And how can I reproduce?

**Comment by matthieumota** [comment]
I think data-target is not used by dropdown but by collapse module https://getbootstrap.com/docs/3.3/components/#navbar-default

**Comment by macdonaldr93** [comment]
Ah yes, you're right. Would you mind just adding an `href="#"` to that anchor tag and doing the same thing to the other dropdown further down the file? Then, I'll merge it.

**Comment by matthieumota** [comment]
I think we can leave it because data-toggle attribute prevent default href link. It can be useful if we want to hover dropdown rather click ?

**Comment by macdonaldr93** [comment]
@MatthieuMota totally. The reason for putting a placeholder `href` is for accessibility, I think it should have had one initial anyways. WCAG requires anchor tags to have hrefs.

**Comment by macdonaldr93** [comment]
@MatthieuMota I'd like this to merge, any progress on the `href`? If you want to merge this, I can open a separate PR for the `href`. Let me know and I'll merge.

**Comment by matthieumota** [comment]
@macdonaldr93 
Oh sorry, actually the href is already present in $item_html by reference with the start_el call. So no need to touch it?
https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/class-walker-nav-menu.php#L117

**Pull request merged**
